Idea CRUD
davinakano/that-awesome-api-nodejs pull request #1
Opened 2020-10-01 16:20 UTC by davinakano

Initial setup of the project, just to have something to work with. Next planned steps are:

- Add tests for those
- Separate dev configuration from prod configuration (use MongoDB locally for dev and MongoDB Atlas for production)
- Add user model / `passport` package configuration for authorization and authentication

2020-10-01 19:57 UTC, rubendess commented on package.json
> +    "start": "nodemon src/app.js",
you can keep the `start` script as node src/app.js and create `start-dev` to run nodemon.

2020-10-01 19:59 UTC, davinakano commented on package.json
> +    "start": "nodemon src/app.js",
Good point! I will change it here, thanks!

2020-10-01 20:04 UTC, rubendess commented on src/controllers/ideas.js
> +const ideaSchema = require('../models/idea');
Ideally, we should manage/handle the business logic in the service layer.

2020-10-01 20:12 UTC, rubendess requested changes
I left some comments, but the main change would be in in the structure, including a service layer.

2020-10-03 02:05 UTC, davinakano commented on src/controllers/ideas.js
> +const ideaSchema = require('../models/idea');
Very good point! I've found an [interesting article](https://www.codementor.io/@evanbechtol/node-service-oriented-architecture-12vjt9zs9i) about this and I tried to follow it (with a grain of salt and trying to make it smaller somehow)

2020-10-03 12:27 UTC, rubendess commented on src/controllers/ideas.js
> +  } catch (err) {
I think that later on we can create our own exceptions, such as "VALIDATION_ERROR", "ITEM_NOT_FOUND", "UNAUTHORIZED", etc etc. And then we can add the error handler on the `app.js`. This way we don't need to add `try catch` statement just to return res.status(500).json({ message: err }).

2020-10-03 12:33 UTC, rubendess commented on src/services/ideaService.js
> +    return { success: true, body: newIdea };
You aren't saving it in the DB. I think you need to call `newIdea.save()`

2020-10-03 12:37 UTC, rubendess commented on src/app.js
I think we need to include the bodyParser here in the app.js.

2020-10-03 12:38 UTC, rubendess approved these changes
I left some comments, but I'm approving.

My main question is about the creation method. I think we're missing the `item.save()` to persist the object in the DB.

2020-10-03 12:40 UTC, rubendess commented on src/controllers/ideas.js
> +const ideaSchema = require('../models/idea');
Very good article! He shows how to add the error handler to the `app.js`

2020-10-04 01:09 UTC, davinakano commented on src/services/ideaService.js
> +    return { success: true, body: newIdea };
My goodness! Completely forgot LOL

2020-10-04 01:14 UTC, davinakano commented on src/controllers/ideas.js
> +  } catch (err) {
Hmmm it would be great to separate those for sure but I am now sure how it would be best to handle those. Should I create a separate constants file? 🤔

2020-10-04 01:16 UTC, davinakano commented on src/app.js
I was reading [this stackoverflow question](https://stackoverflow.com/questions/38306569/what-does-body-parser-do-with-express) and I don't think I understand why bodyParser exists. Could you explain to me later in very very easy terms? :(

2020-10-04 16:17 UTC, merged